# Generated by Django 5.2.4 on 2025-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'inactive'), (5, 'banned')], default=1)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members_userdata',
                'managed': False,
            },
        ),
    ]
